### ISSUE TITLE
API Deployment Improvement

### ISSUE THREAD

**Issue by mlajkim** [ajktown/helm-charts#2]
# Background
We believe that we can take an advantage of usingd`envFrom` instead of using specific `env`
```yaml
  envFrom:
    - configMapRef:
        name: ajktown-api-cm
```
## TODOs
- [ ] Modify the deployment
